function tbl = getNativeLanguageClasses

tonalLanguages = {'Bamwe',...
    'Basa',...
    'Bemba',...
    'Bobangi',...
    'Bukusu',...
    'Burmese',...
    'Cayuga',...
    'Cherokee',...
    'Chewa',...
    'Chinese/Cantonese/Yue',...
    'Chinese/Danzhou',...
    'Chinese/Gan',...
    'Chinese/Hakka',...
    'Chinese/Hokkien',...
    'Chinese/Mandarin',...
    'Chinese/Min Bei',...
    'Chinese/Min Dong',...
    'Chinese/Min Zhong',...
    'Chinese/Pu Xian',...
    'Chinese/Qiong Wen',...
    'Chinese/Shao Jiang',...
    'Chinese/Shaozhou Tuhua',...
    'Chinese/Taiwanese/Min Nan/Hokkien',...
    'Chinese/Wu/Shanghainese',...
    'Chinese/Xiang/Hunanese',...
    'Chinese/Xianghua',...
    'Chinese/Yue',...
    'Denya',...
    'Duma',...
    'Eggon',...
    'Ejagham',...
    'Ekegusii',...
    'Emakua',...
    'Ewe',...
    'Fang',...
    'Ganda',...
    'Gevove',...
    'Hakka',...
    'Hausa',...
    'Hmong',...
    'Holoholo',...
    'Igbo',...
    'Kalanga',...
    'Kinyarwanda',...
    'Koromfé',...
    'Lao',...
    'Lozi',...
    'Mixtec',...
    'Navajo',...
    'Onondaga',...
    'Pende',...
    'Pirahã',...
    'Pulaar',...
    'Shi',...
    'Shona',...
    'Thai',...
    'Tibetan',...
    'Twi',...
    'Vietnamese',...
    'Xhosa',...
    'Yaka',...
    'Yoruba',...
    'Zulu'};
pitchAccentedLanguages = {'Bosnian','Bukusu','Burmese','Cheyenne','Chickasaw','Croatian','Japanese','Lithuanian','Macedonian',...
'Norwegian','Punjabi','Serbian','Slovene','Somali','Swedish','Sūdovian'};
mixed = {'Apache','Algerian','Bantu','Berber','Bisaya','Carib','Chinook','Creole','Eskimo','Other','Popoluca'};

load langPlusScoreTable.mat

uLangs = unique(tbl.nativeLang);
nLangs = length(uLangs);
nSubjects = size(tbl,1);

langClass = cell(nSubjects,1);
for k=1:nLangs
     whichOnes = strcmp(tbl.nativeLang,uLangs{k});
     if any(strcmp(uLangs{k},tonalLanguages))
         indices = find(whichOnes);
         nIndices = sum(whichOnes);
         for h=1:nIndices
            langClass{indices(h)} = 'tonal';
         end
     elseif any(strcmp(uLangs{k},pitchAccentedLanguages))
         indices = find(whichOnes);
         nIndices = sum(whichOnes);
         for h=1:nIndices
            langClass{indices(h)} = 'PA';
         end
     elseif any(strcmp(uLangs{k},mixed))
         indices = find(whichOnes);
         nIndices = sum(whichOnes);
         for h=1:nIndices
            langClass{indices(h)} = 'mixed';
         end
     else
         indices = find(whichOnes);
         nIndices = sum(whichOnes);
         for h=1:nIndices
            langClass{indices(h)} = 'other';
         end
     end
end
tbl.langClass = langClass;
end